name: videomanager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http:  
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.4
  flutter_screenutil: ^5.5.3+2
  file_picker: ^4.5.1
  video_player: ^2.4.4
  map: ^1.0.1
  latlng: ^0.1.0
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.1.1+1
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  touchable: ^1.0.2
  get_storage: ^2.0.3
  data_table_2: ^2.3.2
  intl: ^0.17.0
  flutter_phoenix: ^1.0.0
  syncfusion_flutter_gauges: ^20.2.36
  dart_vlc: ^0.3.0
  universal_platform: ^1.0.0+1
  socket_io_client: ^2.0.0
  audioplayers: ^1.0.1
  timer_builder: ^2.0.0
  get_time_ago: ^1.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/credit-card.png
    - assets/images/nodata.png
    - assets/images/nointernet.png
    - assets/images/Oval.png
    - assets/images/rejected.png
    - assets/images/rejected.svg
    - assets/images/award.png
    - assets/images/wallpaper.jpg
    - assets/images/typing.webp
    - assets/sounds/message_sent.mp3
    - assets/sounds/message_received.mp3
    - assets/sounds/message_delivered.mp3
    - assets/sounds/message_typing.mp3
    - assets/sounds/message_notification.mp3
    - assets/animation/typing_animation.gif

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ibm
      fonts:
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300 
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-ThinItalic.ttf
          weight: 100
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400 
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600 
    - family: PublicSans
      fonts:
        - asset: assets/fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PublicSans-Regular.ttf
          weight: 400 
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600 
    - family: Videomanager
      fonts:
        - asset: assets/fonts/Videomanager.ttf
          weight: 400
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
