/// Flutter icons Videomanager
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Videomanager
///      fonts:
///       - asset: fonts/Videomanager.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class Videomanager {
  Videomanager._();

  static const _kFontFam = 'Videomanager';
  static const String? _kFontPkg = null;

  static const IconData arrow_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assign = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full_screen = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outlets = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_video = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData theater = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_file = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_file = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_setting = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData maps = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usersettings = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videoedit = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usersoutline = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videooutline = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_user_svgrepo_com_1 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_1 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_pin = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sucess = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
